### ISSUE TITLE
Problems when parse function-like macro

### ISSUE THREAD

**Issue by liwangqian** [facebookresearch/CParser#3]
Hi, I encountered a problem when defining function-like macro like:
```c
#define F_MACRO(arg1, arg2, args...) \
    do_f(arg1, arg2, ##args)
```
When parse this code, it raise an error tells that the last argument `args...` is bad. But this code is compile in gcc.

**Comment by leonbottou** [comment]
The supported syntax in C99 is
```c
#define F_MACRO(arg1, arg2, ...) \
    do_f(arg1, arg2, __VA_ARGS__)
```
The Cparser preprocessor contains an extension that accepts invocations of the form `F_MACRO(a,b)`. When this happens, the macro argument `__VA_ARGS__` has the special meaning of removing
any preceding comma when it is followed by a closing parenthesis.

The syntax you describe
```c
#define F_MACRO(arg1, arg2, args...) \
    do_f(arg1, arg2, ##args)
```
contains two GCC extensions at once. The first extension `args...` creates a variadic macro argument with a name different from `__VA_ARGS__`. The second extension solves the negative comma problem by completely modifying the meaning of the concatenation operator `##` when it appears between a comma and a variadic macro argument. 

This kind of subtleties is exactly why preprocessing C is much harder than parsing C. Anyway I forgot to implement these GCC extensions when I wrote it.  This is fixed now:

- Commit [c903e41](https://github.com/facebookresearch/CParser/commit/c903e41fc24b3ac0e0a98bce3f269a2828c38aeb) implements both extensions (with a testfile)
- Commit [8484cd4](https://github.com/facebookresearch/CParser/commit/8484cd4ce5567f2f47e5a63fe45e9911233ad635) restricts these extension to the Gnu dialect (which is the default).
- Commit [f6689dd](https://github.com/facebookresearch/CParser/commit/f6689dd3c55b809c5669928cf74782f482fd2d6a) makes all variants consistent in how they preserve the trailing spaces.

There is also a test file `tests/testvarmacro.c` that exercises the three variants
```c
#define F_MACRO1(arg1, arg2, ...) \
    do_f(arg1, arg2, __VA_ARGS__)
#define F_MACRO2(arg1, arg2, args...) \
    do_f(arg1, arg2, args)
#define F_MACRO3(arg1, arg2, args...) \
    do_f(arg1, arg2, ##args)
```
and expands as
```c
#line 11 "tests/testvarmacro.c"
extern void do_f(int,...);
#line 13 "tests/testvarmacro.c"
int main(int argc, char **argv)
{
	do_f(argc, argv[0], argv[1],argv[2],argv[3]);
	do_f(argc, argv[0] );
	do_f(argc, argv[0], argv[1],argv[2],argv[3]);
	do_f(argc, argv[0], );
	do_f(argc, argv[0],argv[1],argv[2],argv[3]);
	do_f(argc, argv[0] );
}
```

**Comment by leonbottou** [comment]
Closed.

**Comment by liwangqian** [comment]
thanks
