### ISSUE TITLE
Error when including from define

### ISSUE THREAD

**Issue by afonso360** [facebookresearch/CParser#4]
Hello,

I've found an issue when processing an `#include` where the path comes from a separate `#define`.
A minimal test case:

```
#define TEST_INCLUDE_MACRO <system/dir/include.h>
#include TEST_INCLUDE_MACRO
```

This causes the following error when executing `./lcdecl -d:include -d:defines ./testcase.c`
```
                [<builtin>:1] define __CPARSER__ = 1
                [<builtin>:3] define __STDC__ = 1
                [<builtin>:6] define __STDC_VERSION__ = 199901L
                [<builtin>:9] define __GNUC__ = 4
                [<builtin>:12] define __GNUC_MINOR__ = 2
+--------------------------
                [../testcase.c:1] define TEST_INCLUDE_MACRO = <system/dir/include.h>
cparser: (../testcase:2) string expected after #include
```

As far as I've been able to determine, the define is processed correctly, but it expands to `<` and stops there.

The testcase works if we change the define to use double quotes instead of angle brackets:
```
#define TEST_INCLUDE_MACRO "system/dir/include.h"
```

**Comment by leonbottou** [comment]
Fixed in https://github.com/facebookresearch/CParser/commit/41da632

Note that computed includes have very strange properties when the header name contains spaces. 
I tried to replicate what gcc does here. See https://gcc.gnu.org/onlinedocs/cpp/Computed-Includes.html
